### ISSUE TITLE
Block other plugins' portals, signs, etc.

### ISSUE THREAD

**Issue by pgmann** [pgmann/SpectatorPlus#30]
_--- Imported from dev.bukkit.org: original issue reported by TheOnlyRealTGS ---_
If possible, it would be cool if you could block entering the _War_ plugin's portal (currently you can enter the game while in spectate mode), clicking _Hunger Games_ join signs, and generally just prevent joining other minigames because it messes a lot of stuff up.

Maybe you could make a list of negated permissions in the config file? Then you would be able to put `-hg.*` and therefore the players wouldn't be able to join Hunger Games.

**Comment by pgmann** [comment]
### Task List

1. **Permission removal**
    - [ ] Store player permissions when `Spectator.enableSpectatorMode()` is called in some kind of List, then remove them from the player.
    - [ ] Handle permissions being added/removed by other plugins or `op`/`deop` during spectate.
    - [ ] Make sure the permissions are added back when `Spectator.disableSpectatorMode()` is called, and the old list gets emptied.
    - [ ] Don't remove permissions if the player has an admin bypass permission granted, called `spectate.admin.bypasswhitelist` (existing permission, maybe split into `spectate.admin.bypass.whitelist` and `spectate.admin.bypass.permissions`?)
    - [ ] Don't ever remove SpectatorPlus permissions, as they don't need to be.

2. **Cancel click events**
    - [ ] Bind to click events and cancel them all if the player involved is spectating (use `LOWEST` priority to cancel before other plugins have a chance to process the event, but they could still ignore this).

3. **Handle teleportation events**
    - [ ] Cancel teleportation events not made by SpectatorPlus or a command (_any other cases?_) using `HIGHEST` priority.
    - [ ] Check for a teleport which has happened anyway and bring the player back to their original location 1 tick later. This could be done using `MONITOR` priority as we will normally just be looking on or firing our own event.
